/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    slides: Slide;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'plugin-ai-instructions': PluginAiInstruction;
    'plugin-ai-ai-jobs': PluginAiAiJob;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    slides: SlidesSelect<false> | SlidesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'plugin-ai-instructions': PluginAiInstructionsSelect<false> | PluginAiInstructionsSelect<true>;
    'plugin-ai-ai-jobs': PluginAiAiJobsSelect<false> | PluginAiAiJobsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'ai-settings': AiSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'ai-settings': AiSettingsSelect<false> | AiSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact' | 'signalCarousel';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (string | null) | Media;
    carousel?: {
      /**
       * Choose and order the slides shown in the carousel.
       */
      slides?: (string | Slide)[] | null;
      autoAdvanceSeconds?: number | null;
      showThumbnails?: boolean | null;
      overlayStrength?: number | null;
      backdropPattern?: ('points' | 'grid' | 'lines' | 'none') | null;
    };
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
    | WhySwitchBlock
    | OptionsBlock
    | ComparisonTableBlock
    | HowToSwitchBlock
    | TestimonialBlock
    | FAQBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * Optional. Fill this in so the image/copy is ready to paste into a new Carousel Slide (Collections → Carousel Slides) once this page is ready to feature on the homepage.
   */
  carouselFeature?: {
    image?: (string | null) | Media;
    /**
     * Category label, e.g. "Email"
     */
    eyebrow?: string | null;
    /**
     * One-line essayistic caption
     */
    line?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  heroImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (string | Post)[] | null;
  categories?: (string | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Slides for the homepage hero carousel. Add slides here, then choose and order them on the homepage (Pages → Home → Hero).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slides".
 */
export interface Slide {
  id: string;
  /**
   * e.g. "Gmail"
   */
  title: string;
  /**
   * e.g. "Google"
   */
  brand: string;
  category: 'email' | 'social' | 'data' | 'storage' | 'voice' | 'media';
  /**
   * One-line essayistic caption shown under the title
   */
  line: string;
  /**
   * Full-bleed background for this slide. Upload a video (mp4) for a looping background, or an image. Falls back to a placeholder panel if left empty.
   */
  background?: (string | null) | Media;
  /**
   * Portrait thumbnail for the slide strip, ideally 340×573px.
   */
  thumbnail?: (string | null) | Media;
  /**
   * Where "Read the study" points. Optional — leave every field empty until the corresponding page exists.
   */
  link?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  /**
   * Lower numbers appear first in the carousel.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: string | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhySwitchBlock".
 */
export interface WhySwitchBlock {
  /**
   * Small label above the heading, e.g. "Why switch"
   */
  eyebrow?: string | null;
  heading: string;
  intro?: string | null;
  benefits?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'whySwitch';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OptionsBlock".
 */
export interface OptionsBlock {
  /**
   * Small label above the heading, e.g. "The options"
   */
  eyebrow?: string | null;
  heading: string;
  intro?: string | null;
  options?:
    | {
        name: string;
        badge?: ('none' | 'editor-pick' | 'free' | 'open-source') | null;
        logo?: (string | null) | Media;
        /**
         * Short line, e.g. "Encrypted email that respects you."
         */
        tagline?: string | null;
        description?: string | null;
        /**
         * e.g. "Free" or "From $4/mo"
         */
        price?: string | null;
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'options';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComparisonTableBlock".
 */
export interface ComparisonTableBlock {
  /**
   * Small label above the heading, e.g. "How they compare"
   */
  eyebrow?: string | null;
  heading: string;
  /**
   * The products being compared, left to right — usually the mainstream app first, then the alternative(s).
   */
  columns?:
    | {
        label: string;
        isFeatured?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Add one cell per row, in the same order as the columns above.
   */
  rows?:
    | {
        feature: string;
        cells?:
          | {
              status?: ('yes' | 'partial' | 'no') | null;
              /**
               * Optional short note shown under the icon
               */
              note?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'comparisonTable';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HowToSwitchBlock".
 */
export interface HowToSwitchBlock {
  /**
   * Small label above the heading, e.g. "How to switch"
   */
  eyebrow?: string | null;
  heading: string;
  intro?: string | null;
  steps?:
    | {
        title: string;
        description: string;
        /**
         * Optional screenshot shown in the sticky panel on desktop.
         */
        media?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'howToSwitch';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlock".
 */
export interface TestimonialBlock {
  quote: string;
  authorName: string;
  /**
   * e.g. "Verified switcher"
   */
  authorRole?: string | null;
  avatar?: (string | null) | Media;
  rating?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonial';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  /**
   * Small label above the heading, e.g. "Questions"
   */
  eyebrow?: string | null;
  heading: string;
  items?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: string | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-ai-instructions".
 */
export interface PluginAiInstruction {
  id: string;
  /**
   * Please don't change this unless you're sure of what you're doing
   */
  'schema-path'?: string | null;
  /**
   * Please don't change this unless you're sure of what you're doing
   */
  'field-type'?: ('text' | 'textarea' | 'upload' | 'richText') | null;
  'relation-to'?: string | null;
  'model-id'?: ('text' | 'richtext' | 'image' | 'tts') | null;
  /**
   * Please reload your collection after applying the changes
   */
  disabled?: boolean | null;
  /**
   * Click 'Compose' to run this custom prompt and generate content
   */
  prompt?: string | null;
  images?:
    | {
        /**
         * Please make sure the image is publicly accessible.
         */
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  system?: string | null;
  layout?: string | null;
  'text-settings'?: {
    provider?: string | null;
    model?: string | null;
    maxTokens?: number | null;
    temperature?: number | null;
    extractAttachments?: boolean | null;
    /**
     * Provider-specific options. Defaults are inherited from AI Settings.
     */
    providerOptions?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  'richtext-settings'?: {
    provider?: string | null;
    model?: string | null;
    maxTokens?: number | null;
    temperature?: number | null;
    extractAttachments?: boolean | null;
    /**
     * Provider-specific options. Defaults are inherited from AI Settings.
     */
    providerOptions?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  'image-settings'?: {
    provider?: string | null;
    model?: string | null;
    /**
     * Provider-specific options. Defaults are inherited from AI Settings.
     */
    providerOptions?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  'tts-settings'?: {
    provider?: string | null;
    model?: string | null;
    voice?: string | null;
    /**
     * Provider-specific options. Defaults are inherited from AI Settings.
     */
    providerOptions?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-ai-ai-jobs".
 */
export interface PluginAiAiJob {
  id: string;
  instructionId: string | PluginAiInstruction;
  task_id: string;
  status?: ('queued' | 'running' | 'completed' | 'failed' | 'canceled') | null;
  progress?: number | null;
  result_id?: string | null;
  error?: string | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'slides';
        value: string | Slide;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null)
    | ({
        relationTo: 'plugin-ai-instructions';
        value: string | PluginAiInstruction;
      } | null)
    | ({
        relationTo: 'plugin-ai-ai-jobs';
        value: string | PluginAiAiJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
        carousel?:
          | T
          | {
              slides?: T;
              autoAdvanceSeconds?: T;
              showThumbnails?: T;
              overlayStrength?: T;
              backdropPattern?: T;
            };
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        whySwitch?: T | WhySwitchBlockSelect<T>;
        options?: T | OptionsBlockSelect<T>;
        comparisonTable?: T | ComparisonTableBlockSelect<T>;
        howToSwitch?: T | HowToSwitchBlockSelect<T>;
        testimonial?: T | TestimonialBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  carouselFeature?:
    | T
    | {
        image?: T;
        eyebrow?: T;
        line?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhySwitchBlock_select".
 */
export interface WhySwitchBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  benefits?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OptionsBlock_select".
 */
export interface OptionsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  options?:
    | T
    | {
        name?: T;
        badge?: T;
        logo?: T;
        tagline?: T;
        description?: T;
        price?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComparisonTableBlock_select".
 */
export interface ComparisonTableBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  columns?:
    | T
    | {
        label?: T;
        isFeatured?: T;
        id?: T;
      };
  rows?:
    | T
    | {
        feature?: T;
        cells?:
          | T
          | {
              status?: T;
              note?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HowToSwitchBlock_select".
 */
export interface HowToSwitchBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        media?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlock_select".
 */
export interface TestimonialBlockSelect<T extends boolean = true> {
  quote?: T;
  authorName?: T;
  authorRole?: T;
  avatar?: T;
  rating?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slides_select".
 */
export interface SlidesSelect<T extends boolean = true> {
  title?: T;
  brand?: T;
  category?: T;
  line?: T;
  background?: T;
  thumbnail?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-ai-instructions_select".
 */
export interface PluginAiInstructionsSelect<T extends boolean = true> {
  'schema-path'?: T;
  'field-type'?: T;
  'relation-to'?: T;
  'model-id'?: T;
  disabled?: T;
  prompt?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  system?: T;
  layout?: T;
  'text-settings'?:
    | T
    | {
        provider?: T;
        model?: T;
        maxTokens?: T;
        temperature?: T;
        extractAttachments?: T;
        providerOptions?: T;
      };
  'richtext-settings'?:
    | T
    | {
        provider?: T;
        model?: T;
        maxTokens?: T;
        temperature?: T;
        extractAttachments?: T;
        providerOptions?: T;
      };
  'image-settings'?:
    | T
    | {
        provider?: T;
        model?: T;
        providerOptions?: T;
      };
  'tts-settings'?:
    | T
    | {
        provider?: T;
        model?: T;
        voice?: T;
        providerOptions?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-ai-ai-jobs_select".
 */
export interface PluginAiAiJobsSelect<T extends boolean = true> {
  instructionId?: T;
  task_id?: T;
  status?: T;
  progress?: T;
  result_id?: T;
  error?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Logo and the "Site index" menu that slides in from the equals-icon button.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The light "Stone" footer shown at the bottom of every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  statement?: string | null;
  brandName?: string | null;
  missionLine?: string | null;
  columns?:
    | {
        heading: string;
        links?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: string | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: string | Post;
                    } | null);
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  copyrightText?: string | null;
  tagline?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-settings".
 */
export interface AiSetting {
  id: string;
  /**
   * Configure which AI providers to use and their settings
   */
  providers: (
    | {
        enabled?: boolean | null;
        /**
         * Optional. If empty, @ai-sdk/openai will use the OPENAI_API_KEY environment variable.
         */
        apiKey?: string | null;
        /**
         * Optional. Override default API endpoint (defaults to https://api.openai.com/v1).
         */
        baseURL?: string | null;
        /**
         * Optional. OpenAI organization ID for billing and access control.
         */
        organization?: string | null;
        /**
         * Optional. OpenAI project ID for organization-level access.
         */
        project?: string | null;
        /**
         * Optional. Extra headers to send with every request, for example routing through a proxy.
         */
        headers?:
          | {
              key: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Available voices for Text-to-Speech models. You can add custom voices here.
         */
        voices?:
          | {
              id: string | null;
              name: string;
              enabled?: boolean | null;
            }[]
          | null;
        /**
         * Default provider options for TTS models. Users can override these per field.
         */
        ttsProviderOptions?: {
          speed?: number | null;
          response_format?: ('mp3' | 'opus' | 'aac' | 'flac' | 'wav' | 'pcm') | null;
          instructions?: string | null;
        };
        /**
         * Default provider options for image generation models.
         */
        imageProviderOptions?: {
          quality?: ('standard' | 'hd') | null;
          style?: ('vivid' | 'natural') | null;
        };
        /**
         * Default provider options for text generation models.
         */
        textProviderOptions?: {
          temperature?: number | null;
          max_tokens?: number | null;
          top_p?: number | null;
          frequency_penalty?: number | null;
          presence_penalty?: number | null;
          seed?: number | null;
          /**
           * Modify likelihood of tokens (JSON object mapping token IDs to bias).
           */
          logitBias?:
            | {
                [k: string]: unknown;
              }
            | unknown[]
            | string
            | number
            | boolean
            | null;
        };
        /**
         * Keep this list short. Enable only the models you actually use.
         */
        models?:
          | {
              id: string | null;
              name: string;
              useCase?: ('text' | 'image' | 'tts' | 'embedding') | null;
              /**
               * Output capabilities of this model
               */
              responseModalities?: ('TEXT' | 'IMAGE' | 'AUDIO')[] | null;
              enabled?: boolean | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'openai';
      }
    | {
        enabled?: boolean | null;
        /**
         * Your Anthropic API key. Will be encrypted in the database.
         */
        apiKey: string;
        /**
         * Default provider options for text generation models.
         */
        textProviderOptions?: {
          temperature?: number | null;
          max_tokens?: number | null;
          top_p?: number | null;
          top_k?: number | null;
        };
        models?:
          | {
              id: string | null;
              name: string;
              useCase?: 'text' | null;
              /**
               * Output capabilities of this model
               */
              responseModalities?: ('TEXT' | 'IMAGE' | 'AUDIO')[] | null;
              enabled?: boolean | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'anthropic';
      }
    | {
        enabled?: boolean | null;
        /**
         * Optional. If empty, @ai-sdk/google will use the GOOGLE_GENERATIVE_AI_API_KEY environment variable.
         */
        apiKey?: string | null;
        /**
         * Optional. Override default API endpoint (defaults to https://generativelanguage.googleapis.com/v1beta).
         */
        baseURL?: string | null;
        /**
         * Optional. Extra headers to send with every request, for example routing through a proxy.
         */
        headers?:
          | {
              key: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Available voices for Gemini TTS models.
         */
        voices?:
          | {
              id: string | null;
              name: string;
              enabled?: boolean | null;
            }[]
          | null;
        /**
         * Default provider options for TTS models.
         */
        ttsProviderOptions?: {
          speed?: number | null;
          volumeGainDb?: number | null;
        };
        /**
         * Default provider options for image generation models.
         */
        imageProviderOptions?: {
          aspectRatio?: ('1:1' | '16:9' | '9:16' | '4:3' | '3:4') | null;
          personGeneration?: ('allow_adult' | 'allow_all' | 'dont_allow') | null;
          addWatermark?: boolean | null;
        };
        /**
         * Default provider options for text generation models.
         */
        textProviderOptions?: {
          temperature?: number | null;
          maxOutputTokens?: number | null;
          topP?: number | null;
          topK?: number | null;
          /**
           * Safety filter settings
           */
          safetySettings?:
            | {
                category:
                  | 'HARM_CATEGORY_HARASSMENT'
                  | 'HARM_CATEGORY_HATE_SPEECH'
                  | 'HARM_CATEGORY_SEXUALLY_EXPLICIT'
                  | 'HARM_CATEGORY_DANGEROUS_CONTENT';
                threshold: 'BLOCK_NONE' | 'BLOCK_LOW_AND_ABOVE' | 'BLOCK_MEDIUM_AND_ABOVE' | 'BLOCK_ONLY_HIGH';
                id?: string | null;
              }[]
            | null;
        };
        /**
         * Keep this list short. Enable only the models you actually use.
         */
        models?:
          | {
              id: string | null;
              name: string;
              useCase?: ('text' | 'image' | 'tts' | 'embedding') | null;
              /**
               * Output capabilities of this model
               */
              responseModalities?: ('TEXT' | 'IMAGE' | 'AUDIO')[] | null;
              enabled?: boolean | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'google';
      }
    | {
        enabled?: boolean | null;
        /**
         * Your xAI API key. Will be encrypted in the database.
         */
        apiKey: string;
        /**
         * Default provider options for text generation models.
         */
        textProviderOptions?: {
          temperature?: number | null;
          max_tokens?: number | null;
          top_p?: number | null;
          frequency_penalty?: number | null;
          presence_penalty?: number | null;
        };
        models?:
          | {
              id: string | null;
              name: string;
              useCase: 'text' | 'image';
              /**
               * Output capabilities of this model
               */
              responseModalities?: ('TEXT' | 'IMAGE' | 'AUDIO')[] | null;
              enabled?: boolean | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'xai';
      }
    | {
        enabled?: boolean | null;
        /**
         * Your ElevenLabs API key. Will be encrypted in the database. Get yours at elevenlabs.io
         */
        apiKey: string;
        /**
         * Optional. Override default API endpoint (defaults to https://api.elevenlabs.io/v1).
         */
        baseURL?: string | null;
        /**
         * Optional. Custom headers to send with every request.
         */
        headers?:
          | {
              key: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Use the "Fetch Voices" button above to populate this list from your ElevenLabs account.
         */
        voices?:
          | {
              id: string | null;
              name: string;
              enabled?: boolean | null;
              category?: ('premade' | 'cloned' | 'professional' | 'generated') | null;
              preview_url?: string | null;
              /**
               * Voice attributes like gender, age, accent (JSON object). Example: {"gender": "female", "age": "young", "accent": "american"}
               */
              labels?:
                | {
                    [k: string]: unknown;
                  }
                | unknown[]
                | string
                | number
                | boolean
                | null;
            }[]
          | null;
        /**
         * Default provider options for ElevenLabs TTS.
         */
        ttsProviderOptions?: {
          voice_settings?: {
            stability?: number | null;
            similarity_boost?: number | null;
            style?: number | null;
            use_speaker_boost?: boolean | null;
          };
          seed?: number | null;
          apply_text_normalization?: ('auto' | 'on' | 'off') | null;
          language_code?: string | null;
        };
        /**
         * Configure TTS models. Use the Voices and Provider Options tabs for detailed settings.
         */
        models?:
          | {
              id: string | null;
              name: string;
              useCase?: 'tts' | null;
              /**
               * Output capabilities of this model
               */
              responseModalities?: ('TEXT' | 'AUDIO')[] | null;
              enabled?: boolean | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'elevenlabs';
      }
    | {
        enabled?: boolean | null;
        /**
         * Your Fal API key. Will be encrypted in the database.
         */
        apiKey: string;
        /**
         * Secret for webhook verification (optional)
         */
        webhookSecret?: string | null;
        /**
         * Default provider options for image generation models.
         */
        imageProviderOptions?: {
          num_inference_steps?: number | null;
          guidance_scale?: number | null;
          /**
           * Random seed for reproducible results
           */
          seed?: number | null;
          image_size?:
            ('square' | 'square_hd' | 'portrait_4_3' | 'portrait_16_9' | 'landscape_4_3' | 'landscape_16_9') | null;
          enable_safety_checker?: boolean | null;
        };
        /**
         * Default provider options for video generation models.
         */
        videoProviderOptions?: {
          duration?: number | null;
          aspect_ratio?: ('16:9' | '9:16' | '1:1') | null;
        };
        models?:
          | {
              id: string | null;
              name: string;
              useCase: 'image' | 'video';
              enabled?: boolean | null;
              /**
               * Output capabilities of this model
               */
              responseModalities?: ('TEXT' | 'IMAGE' | 'AUDIO' | 'VIDEO')[] | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'fal';
      }
    | {
        /**
         * Display name for this custom provider (e.g., "Ollama", "Together AI")
         */
        providerName: string;
        enabled?: boolean | null;
        /**
         * API key for this provider (if required)
         */
        apiKey: string;
        /**
         * OpenAI-compatible API endpoint (e.g., http://localhost:11434/v1)
         */
        baseURL: string;
        /**
         * Default provider options for text generation models.
         */
        textProviderOptions?: {
          temperature?: number | null;
          max_tokens?: number | null;
          top_p?: number | null;
          frequency_penalty?: number | null;
          presence_penalty?: number | null;
        };
        /**
         * Default provider options for image generation models.
         */
        imageProviderOptions?: {
          quality?: ('standard' | 'hd') | null;
          style?: ('vivid' | 'natural') | null;
        };
        /**
         * Default provider options for TTS models.
         */
        ttsProviderOptions?: {
          speed?: number | null;
          response_format?: ('mp3' | 'opus' | 'aac' | 'flac' | 'wav') | null;
        };
        models?:
          | {
              id: string | null;
              name: string;
              useCase: 'text' | 'image' | 'video' | 'tts';
              enabled?: boolean | null;
              /**
               * Output capabilities of this model
               */
              responseModalities?: ('TEXT' | 'IMAGE' | 'AUDIO')[] | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'openai-compatible';
      }
  )[];
  /**
   * Default provider/model behavior for each use case
   */
  defaults?: {
    text?: {
      provider?: string | null;
      model?: string | null;
      /**
       * Default options for this model (global)
       */
      options?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
    image?: {
      provider?: string | null;
      model?: string | null;
      /**
       * Default options for this model (global)
       */
      options?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
    video?: {
      provider?: string | null;
      model?: string | null;
      /**
       * Default options for this model (global)
       */
      options?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
    tts?: {
      provider?: string | null;
      model?: string | null;
      voice?: string | null;
      /**
       * Default options for this model (global)
       */
      options?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  statement?: T;
  brandName?: T;
  missionLine?: T;
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  copyrightText?: T;
  tagline?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-settings_select".
 */
export interface AiSettingsSelect<T extends boolean = true> {
  providers?:
    | T
    | {
        openai?:
          | T
          | {
              enabled?: T;
              apiKey?: T;
              baseURL?: T;
              organization?: T;
              project?: T;
              headers?:
                | T
                | {
                    key?: T;
                    value?: T;
                    id?: T;
                  };
              voices?:
                | T
                | {
                    id?: T;
                    name?: T;
                    enabled?: T;
                  };
              ttsProviderOptions?:
                | T
                | {
                    speed?: T;
                    response_format?: T;
                    instructions?: T;
                  };
              imageProviderOptions?:
                | T
                | {
                    quality?: T;
                    style?: T;
                  };
              textProviderOptions?:
                | T
                | {
                    temperature?: T;
                    max_tokens?: T;
                    top_p?: T;
                    frequency_penalty?: T;
                    presence_penalty?: T;
                    seed?: T;
                    logitBias?: T;
                  };
              models?:
                | T
                | {
                    id?: T;
                    name?: T;
                    useCase?: T;
                    responseModalities?: T;
                    enabled?: T;
                  };
              id?: T;
              blockName?: T;
            };
        anthropic?:
          | T
          | {
              enabled?: T;
              apiKey?: T;
              textProviderOptions?:
                | T
                | {
                    temperature?: T;
                    max_tokens?: T;
                    top_p?: T;
                    top_k?: T;
                  };
              models?:
                | T
                | {
                    id?: T;
                    name?: T;
                    useCase?: T;
                    responseModalities?: T;
                    enabled?: T;
                  };
              id?: T;
              blockName?: T;
            };
        google?:
          | T
          | {
              enabled?: T;
              apiKey?: T;
              baseURL?: T;
              headers?:
                | T
                | {
                    key?: T;
                    value?: T;
                    id?: T;
                  };
              voices?:
                | T
                | {
                    id?: T;
                    name?: T;
                    enabled?: T;
                  };
              ttsProviderOptions?:
                | T
                | {
                    speed?: T;
                    volumeGainDb?: T;
                  };
              imageProviderOptions?:
                | T
                | {
                    aspectRatio?: T;
                    personGeneration?: T;
                    addWatermark?: T;
                  };
              textProviderOptions?:
                | T
                | {
                    temperature?: T;
                    maxOutputTokens?: T;
                    topP?: T;
                    topK?: T;
                    safetySettings?:
                      | T
                      | {
                          category?: T;
                          threshold?: T;
                          id?: T;
                        };
                  };
              models?:
                | T
                | {
                    id?: T;
                    name?: T;
                    useCase?: T;
                    responseModalities?: T;
                    enabled?: T;
                  };
              id?: T;
              blockName?: T;
            };
        xai?:
          | T
          | {
              enabled?: T;
              apiKey?: T;
              textProviderOptions?:
                | T
                | {
                    temperature?: T;
                    max_tokens?: T;
                    top_p?: T;
                    frequency_penalty?: T;
                    presence_penalty?: T;
                  };
              models?:
                | T
                | {
                    id?: T;
                    name?: T;
                    useCase?: T;
                    responseModalities?: T;
                    enabled?: T;
                  };
              id?: T;
              blockName?: T;
            };
        elevenlabs?:
          | T
          | {
              enabled?: T;
              apiKey?: T;
              baseURL?: T;
              headers?:
                | T
                | {
                    key?: T;
                    value?: T;
                    id?: T;
                  };
              voices?:
                | T
                | {
                    id?: T;
                    name?: T;
                    enabled?: T;
                    category?: T;
                    preview_url?: T;
                    labels?: T;
                  };
              ttsProviderOptions?:
                | T
                | {
                    voice_settings?:
                      | T
                      | {
                          stability?: T;
                          similarity_boost?: T;
                          style?: T;
                          use_speaker_boost?: T;
                        };
                    seed?: T;
                    apply_text_normalization?: T;
                    language_code?: T;
                  };
              models?:
                | T
                | {
                    id?: T;
                    name?: T;
                    useCase?: T;
                    responseModalities?: T;
                    enabled?: T;
                  };
              id?: T;
              blockName?: T;
            };
        fal?:
          | T
          | {
              enabled?: T;
              apiKey?: T;
              webhookSecret?: T;
              imageProviderOptions?:
                | T
                | {
                    num_inference_steps?: T;
                    guidance_scale?: T;
                    seed?: T;
                    image_size?: T;
                    enable_safety_checker?: T;
                  };
              videoProviderOptions?:
                | T
                | {
                    duration?: T;
                    aspect_ratio?: T;
                  };
              models?:
                | T
                | {
                    id?: T;
                    name?: T;
                    useCase?: T;
                    enabled?: T;
                    responseModalities?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'openai-compatible'?:
          | T
          | {
              providerName?: T;
              enabled?: T;
              apiKey?: T;
              baseURL?: T;
              textProviderOptions?:
                | T
                | {
                    temperature?: T;
                    max_tokens?: T;
                    top_p?: T;
                    frequency_penalty?: T;
                    presence_penalty?: T;
                  };
              imageProviderOptions?:
                | T
                | {
                    quality?: T;
                    style?: T;
                  };
              ttsProviderOptions?:
                | T
                | {
                    speed?: T;
                    response_format?: T;
                  };
              models?:
                | T
                | {
                    id?: T;
                    name?: T;
                    useCase?: T;
                    enabled?: T;
                    responseModalities?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  defaults?:
    | T
    | {
        text?:
          | T
          | {
              provider?: T;
              model?: T;
              options?: T;
            };
        image?:
          | T
          | {
              provider?: T;
              model?: T;
              options?: T;
            };
        video?:
          | T
          | {
              provider?: T;
              model?: T;
              options?: T;
            };
        tts?:
          | T
          | {
              provider?: T;
              model?: T;
              voice?: T;
              options?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}